spring.application.name=tsl-timing-api
spring.ai.openai.api-key=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
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=100MB


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## JWT Configuration
security.jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
security.jwt.issuer=starlane api
security.jwt.expiration=900
